RIA-7318 - Java 17 Upgrade - updating serenity to 3.2.3
Serenity versions above 3.2.3 appear to break the build, if the issue below persists within Jenkins, I will look to update this version past 3.2.3, which will likely incur further upgrades to other dependencies.

This is attempting to fix issue:
"Where:
Build file '/opt/jenkins/workspace/S_d_to_i_ia-bail-case-api_PR-351/build.gradle' line: 26

What went wrong:
A problem occurred evaluating root project 'S_d_to_i_ia-bail-case-api_PR-351'.
Failed to apply plugin 'net.serenity-bdd.aggregator'.
java.lang.IllegalStateException: Unable to load cache item"